language: php

dist: bionic

# php compatibility
php:
  - "7.3"

addons:
  apt:
    packages:
      - default-jre-headless
      - libreoffice-calc
      - xlsx2csv

before_script:
  - phpenv config-rm xdebug.ini || true
  - travis_retry composer self-update --stable --2 --no-interaction
  - travis_retry composer update --no-interaction --prefer-dist

script:
  - vendor/bin/php-cs-fixer fix --verbose
  - vendor/bin/phpcbf --colors -sp src/ tests/
  - php vendor/bin/phpunit --testdox
  - vendor/bin/phpstan.phar analyse --no-progress --level max src/ tests/
  - bin/sat-catalogos-update dump-origins > build/origins.xml
  - bin/sat-catalogos-update update-origins build/ -w build/database.sqlite3

notifications:
  email:
    if: branch = master
